db:
  build: ./containers/db
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: pass
  volumes:
    - db:/var/lib/mysql
    - ./containers/db:/var/tmp/mysql
#  entrypoint: /var/tmp/mysql/entrypoint.sh
  container_name: db
web:
  build: .
  restart: always
  ports:
    - '80:8080'
  volumes:
    - .:/var/www/html
    - ./containers/web/log:/var/log/nginx
  environment:
    MYSQL_DATABASE: mydb
    MYSQL_USER: myservice
    MYSQL_PASSWORD: secret
  links:
    - db
    - memcached
  working_dir: /var/www/html
  container_name: web
memcached:
  image: memcached
  restart: always
  container_name: memcached
